apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-getalltasks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-getalltasks
  template:
    metadata:
      labels:
        app: microservices-getalltasks
    spec:
      containers:
        - name: microservices-getalltasks
          image: omeratt/microserveices-getalltasks:latest
          ports:
            - containerPort: 8006
